name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check code
        run: pnpm check

      - name: Run tests
        run: pnpm test:run

      - name: Build app
        run: pnpm build

      - name: Deploy to Netlify
        if: ${{ github.event_name == 'push' }}
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: dist
          production-deploy: true
          netlify-config-path: netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
